---

# - git:
#     repo: https://github.com/rbenv/rbenv.git
#     dest: '{{ ansible_env.HOME }}/.rbenv'
#
# - git:
#     repo: https://github.com/rbenv/ruby-build.git
#     dest: '{{ ansible_env.HOME }}/.rbenv/plugins/ruby-build'

- apt:
    name:
      - autoconf
      - bison
      - build-essential
      - libdb-dev
      - libffi-dev
      - libgdbm-dev
      - libgdbm6
      - libncurses5-dev
      - libreadline6-dev
      - libssl-dev
      - libyaml-dev
      - zlib1g-dev
    state: latest
  become: yes

