---

- apt: name={{ item }} state=latest
  become: yes
  with_items:
    - ctags
    - gcc
    - git
    - make
    - vim
    - zsh
    - source-highlight

- name: install requirements for cpsm(vim plugin)
  apt: name={{ item }} state=latest
  become: yes
  with_items:
    - libboost-all-dev
    - cmake
    - python-dev
    - libicu-dev

