---

- apt:
    name:
      - ctags
      - gcc
      - git
      - make
      - source-highlight
      - tig
      - vim
      - zsh
    state: latest
  become: yes

- name: install requirements for cpsm(vim plugin)
  apt:
    name:
      - cmake
      - libboost-all-dev
      - libicu-dev
      - python-dev
      - python3-dev
    state: latest
  become: yes

