tap "delphinus/sfmono-square"
tap "homebrew/bundle"
tap "homebrew/core", "https://github.com/Homebrew/linuxbrew-core.git"
tap "linuxbrew/extra"
tap "linuxbrew/xorg"
brew "anyenv"
brew "exa"
brew "fd"
brew "gibo"
brew "ninja"
brew "ripgrep"
brew "zsh"
brew "delphinus/sfmono-square/sfmono-square"
