tap "burntsushi/ripgrep", "https://github.com/BurntSushi/ripgrep.git"
# tap "delphinus/sfmono-square"
tap "homebrew/bundle"
tap "homebrew/core", "https://github.com/Homebrew/linuxbrew-core.git"
tap "linuxbrew/extra"
tap "linuxbrew/xorg"
brew "anyenv"
brew "bat"
brew "burntsushi/ripgrep/ripgrep-bin"
brew "cmake"
# brew "delphinus/sfmono-square/sfmono-square"
brew "exa"
brew "fd"
brew "fish"
brew "fselect"
brew "fzf"
brew "gibo"
brew "jq"
brew "kubernetes-cli"
brew "kubectx"
brew "lsd"
brew "meson"
brew "ninja"
# brew "pipenv"
brew "rargs"
brew "stern"
brew "terraformer"
brew "tfenv"
brew "tmux"
brew "the_platinum_searcher"
brew "the_silver_searcher"
brew "zsh"
brew "starship"
