tap "burntsushi/ripgrep", "https://github.com/BurntSushi/ripgrep.git"
# tap "delphinus/sfmono-square"
tap "homebrew/bundle"
tap "homebrew/core", "https://github.com/Homebrew/linuxbrew-core.git"
tap "linuxbrew/extra"
tap "linuxbrew/xorg"
brew "anyenv"
brew "burntsushi/ripgrep/ripgrep-bin"
brew "cmake"
# brew "delphinus/sfmono-square/sfmono-square"
brew "exa"
brew "fd"
brew "fish"
brew "gibo"
brew "jq"
brew "ninja"
# brew "pipenv"
brew "the_platinum_searcher"
brew "the_silver_searcher"
brew "zsh"
