---

- apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes
  become: yes

- apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
  become: yes

- apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: yes

- apt:
    name: docker-ce
    state: latest
  become: yes

- service:
    name: docker
    state: started
    enabled: yes
  become: yes

- group:
    name: docker
    state: present
  become: yes

- user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: yes

- get_url:
    url: https://github.com/docker/compose/releases/download/1.23.1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: a+x
  become: yes

