---

- file:
    path: "{{ ansible_env.HOME }}/src"
    state: directory

- get_url:
    url: https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz
    dest: "{{ ansible_env.HOME }}/src/go1.7.4.linux-amd64.tar.gz"
    checksum: sha256:47fda42e46b4c3ec93fa5d4d4cc6a748aa3f9411a2a2b7e08e3a6d80d753ec8b

- command: "{{ ansible_env.HOME }}/go/bin/go version"
  ignore_errors: yes
  register: go_version
  changed_when: false

- file:
    path: "{{ ansible_env.HOME }}/go"
    state: absent
  when: go_version|failed or go_version.stdout != "go version go1.7.4 linux/amd64"

- unarchive:
    src: "{{ ansible_env.HOME }}/src/go1.7.4.linux-amd64.tar.gz"
    dest: "{{ ansible_env.HOME }}"
    remote_src: yes
  when: go_version|failed or go_version.stdout != "go version go1.7.4 linux/amd64"

