---

- file:
    path: "{{ ansible_env.HOME }}/src"
    state: directory

- get_url:
    url: "https://storage.googleapis.com/golang/go{{ go_target_version }}.linux-amd64.tar.gz"
    dest: "{{ ansible_env.HOME }}/src/go{{ go_target_version }}.linux-amd64.tar.gz"
    checksum: "{{ go_target_version_checksum }}"

- command: "{{ ansible_env.HOME }}/go/bin/go version"
  ignore_errors: yes
  register: go_version
  changed_when: false

- file:
    path: "{{ ansible_env.HOME }}/go"
    state: absent
  when: go_version|failed or go_version.stdout != "go version go{{ go_target_version }} linux/amd64"

- unarchive:
    src: "{{ ansible_env.HOME }}/src/go{{ go_target_version }}.linux-amd64.tar.gz"
    dest: "{{ ansible_env.HOME }}"
    remote_src: yes
  when: go_version|failed or go_version.stdout != "go version go{{ go_target_version }} linux/amd64"

