---

- block:
    - apt_repository:
        repo: 'ppa:neovim-ppa/stable'
      become: yes

    - apt:
        name: neovim
        state: latest
      become: yes

    - apt:
        name:
          - python-dev
          - python-pip
          - python3-dev
          - python3-pip
        state: latest
      become: yes

    - pip:
        name: neovim
        state: latest
        executable: pip3
      become: yes

  tags: neovim

