---

- apt_repository:
    repo: 'ppa:neovim-ppa/unstable'
  become: yes

- apt:
    name: neovim
    state: latest
  become: yes

- apt:
    name: '{{ item }}'
    state: latest
  become: yes
  with_items:
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip

- pip:
    name: neovim
    state: latest
    executable: pip3
  become: yes
