---

- apt:
    name:
      - build-essential
      - curl
      - libbz2-dev
      - libffi-dev
      - liblzma-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - llvm
      - make
      - python3-openssl
      - tk-dev
      - wget
      - xz-utils
      - zlib1g-dev
    state: present
  become: yes

