---

- hosts: localhost
  connection: local
  roles:
    - { role: common }
    - { role: tmux }
    - { role: neovim }
    - { role: golang }
    - { role: docker }
    - { role: anyenv }
    - { role: ricty-for-powerline }

