[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
on_i = 1
hook_source = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'zchee/deoplete-go'
if = "has('nvim')"
build = 'make'
on_i = 1
on_ft = 'go'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css']

