[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# ----- textobj -----
[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-entire'

[[plugins]]
repo = 'kana/vim-textobj-line'

# [[plugins]]
# repo = 'kana/vim-textobj-function'

[[plugins]]
repo = 'kana/vim-textobj-underscore'

[[plugins]]
repo = 'thinca/vim-textobj-between'

[[plugins]]
repo = 'thinca/vim-textobj-comment'

[[plugins]]
repo = 'sgur/vim-textobj-parameter'

[[plugins]]
repo = 'kana/vim-textobj-jabraces'

[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'

# ----- operator -----
[[plugins]]
repo = 'kana/vim-operator-user'
[[plugins]]
repo = 'emonkak/vim-operator-sort'

[[plugins]]
repo = 'kana/vim-operator-replace'

[[plugins]]
repo = 'rhysd/vim-operator-surround'

[[plugins]]
repo = 'tyru/operator-camelize.vim'

# ----- unite -----
[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'Shougo/junkfile.vim'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'thinca/vim-qfreplace'

[[plugins]]
repo = 'tsukkee/unite-tag'

[[plugins]]
repo = 'thinca/vim-unite-history'

[[plugins]]
repo = 'osyo-manga/unite-filetype'

[[plugins]]
repo = 'Shougo/unite-sudo'

[[plugins]]
repo = 'sorah/unite-ghq'

[[plugins]]
repo = 'Shougo/unite-build'

[[plugins]]
repo = 'Shougo/unite-help'

[[plugins]]
repo = 'Kocha/vim-unite-tig'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'ujihisa/unite-rake'

[[plugins]]
repo = 'basyura/unite-rails'

# ----- utility -----
[[plugins]]
repo = 'renamer.vim'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'othree/eregex.vim'

[[plugins]]
repo = 'sjl/gundo.vim'

[[plugins]]
repo = 't9md/vim-textmanip'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'neomake/neomake'
hook_add = '''
  autocmd! BufWritePost * Neomake
'''

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'cocopon/vaffle.vim'

[[plugins]]
repo = 'justinmk/vim-dirvish'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'nixprime/cpsm'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'lambdalisue/vim-findent'

[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'

[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]
repo = 'cohama/vim-smartinput-endwise'
hook_source = 'call smartinput_endwise#define_default_rules()'

# ----- syntax -----
[[plugins]]
repo = 'vim-jp/cpp-vim'
on_ft = 'cpp'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'chase/vim-ansible-yaml'

[[plugins]]
repo = 'cespare/vim-toml'

# ----- colorscheme -----
[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'aereal/vim-colors-japanesque'

[[plugins]]
repo = 'vim-scripts/jammy.vim'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'reedes/vim-colors-pencil'

[[plugins]]
repo = 'vim-scripts/twilight'

[[plugins]]
repo = 'jonathanfilip/vim-lucius'

[[plugins]]
repo = 'jpo/vim-railscasts-theme'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'vim-scripts/Wombat'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'vim-scripts/rdark'

[[plugins]]
repo = 'mrkn/mrkn256.vim'

