# ----- utility -----
[[plugins]]
repo = 'kana/vim-submode'
on_event = ['VimEnter']
hook_post_source = '''
" window
call submode#enter_with('winsize', 'n', '', '<C-w>>', '<C-w>>')
call submode#enter_with('winsize', 'n', '', '<C-w><', '<C-w><')
call submode#enter_with('winsize', 'n', '', '<C-w>+', '<C-w>+')
call submode#enter_with('winsize', 'n', '', '<C-w>-', '<C-w>-')
call submode#map('winsize', 'n', '', '>', '<C-w>>')
call submode#map('winsize', 'n', '', '<', '<C-w><')
call submode#map('winsize', 'n', '', '+', '<C-w>+')
call submode#map('winsize', 'n', '', '-', '<C-w>-')
" tab
call submode#enter_with('movetab', 'n', '', '<C-t>l', ':<C-u>+tabmove<CR>')
call submode#enter_with('movetab', 'n', '', '<C-t>h', ':<C-u>-tabmove<CR>')
call submode#map('movetab', 'n', '', 'l', ':<C-u>+tabmove<CR>')
call submode#map('movetab', 'n', '', 'h', ':<C-u>-tabmove<CR>')
'''

# ----- golang -----
[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = 'go'

# ----- HTML -----
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'php']

# ----- Ruby -----
[[plugins]]
repo = 'tpope/vim-rails'
on_ft = 'ruby'

# ----- denite -----
[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_event = 'TextYankPost'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Shougo/junkfile.vim'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = ['denite.nvim']

[[plugins]]
repo = 'tsukkee/unite-tag'
on_source = ['denite.nvim']

[[plugins]]
repo = 'thinca/vim-unite-history'
on_source = ['denite.nvim']

[[plugins]]
repo = 'osyo-manga/unite-filetype'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Shougo/unite-sudo'
on_source = ['denite.nvim']

[[plugins]]
repo = 'sorah/unite-ghq'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Shougo/unite-build'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Shougo/unite-help'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Kocha/vim-unite-tig'
on_source = ['denite.nvim']

[[plugins]]
repo = 'ujihisa/unite-colorscheme'
on_source = ['denite.nvim']

[[plugins]]
repo = 'ujihisa/unite-rake'
on_source = ['denite.nvim']

[[plugins]]
repo = 'basyura/unite-rails'
on_source = ['denite.nvim']

[[plugins]]
repo = 'rhysd/unite-ruby-require.vim'
on_source = ['denite.nvim']
