# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# if = "has('nvim')"
# on_event = 'InsertEnter'
# hook_source = 'let g:deoplete#enable_at_startup = 1'

# ----- C++ -----
[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'
on_ft = 'cpp'

# libclang を使った syntax highligh
# インストールが一手間なのであとで試す
# [[plugins]]
# repo = 'jeaye/color_coded'
# on_ft = 'cpp'
# 
# [[plugins]]
# repo = 'arakashic/chromatica.nvim'
# on_ft = 'cpp'

# ----- golang -----
# [[plugins]]
# repo = 'zchee/deoplete-go'
# if = "has('nvim')"
# build = 'make'
# on_ft = 'go'
# on_event = 'InsertEnter'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

# ----- HTML -----
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css']

# ----- Ruby -----
# [[plugins]]
# repo = 'fishbullet/deoplete-ruby'
# on_ft = 'ruby'

# [[plugins]]
# repo = 'uplus/deoplete-solargraph'
# on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = 'ruby'

[[plugins]]
repo = 'todesking/ruby_hl_lvar.vim'
on_ft = 'ruby'

# ----- denite -----
[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Shougo/junkfile.vim'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = ['denite.nvim']

[[plugins]]
repo = 'thinca/vim-qfreplace'
on_source = ['denite.nvim']

[[plugins]]
repo = 'tsukkee/unite-tag'
on_source = ['denite.nvim']

[[plugins]]
repo = 'thinca/vim-unite-history'
on_source = ['denite.nvim']

[[plugins]]
repo = 'osyo-manga/unite-filetype'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Shougo/unite-sudo'
on_source = ['denite.nvim']

[[plugins]]
repo = 'sorah/unite-ghq'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Shougo/unite-build'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Shougo/unite-help'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Kocha/vim-unite-tig'
on_source = ['denite.nvim']

[[plugins]]
repo = 'ujihisa/unite-colorscheme'
on_source = ['denite.nvim']

[[plugins]]
repo = 'ujihisa/unite-rake'
on_source = ['denite.nvim']

[[plugins]]
repo = 'basyura/unite-rails'
on_source = ['denite.nvim']

[[plugins]]
repo = 'rhysd/unite-ruby-require.vim'
on_source = ['denite.nvim']

# ----- utility -----

