# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# if = "has('nvim')"
# on_event = 'InsertEnter'
# hook_source = 'let g:deoplete#enable_at_startup = 1'

# ----- C++ -----
[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'
on_ft = 'cpp'

# libclang を使った syntax highligh
# インストールが一手間なのであとで試す
# [[plugins]]
# repo = 'jeaye/color_coded'
# on_ft = 'cpp'
# 
# [[plugins]]
# repo = 'arakashic/chromatica.nvim'
# on_ft = 'cpp'

# ----- golang -----
# [[plugins]]
# repo = 'zchee/deoplete-go'
# if = "has('nvim')"
# build = 'make'
# on_ft = 'go'
# on_event = 'InsertEnter'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

# ----- HTML -----
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css']

# ----- Ruby -----
# [[plugins]]
# repo = 'fishbullet/deoplete-ruby'
# on_ft = 'ruby'

# [[plugins]]
# repo = 'uplus/deoplete-solargraph'
# on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = 'ruby'

[[plugins]]
repo = 'todesking/ruby_hl_lvar.vim'
on_ft = 'ruby'

# ----- utility -----

