# ----- nvim-cmp -----
[[plugins]]
repo = 'hrsh7th/nvim-cmp'
if = 'has("nvim")'
depends = [
  'cmp-nvim-lsp',
  'cmp-buffer',
  'cmp-path',
  'cmp-cmdline',
  'cmp-vsnip',
  'cmp-fuzzy-buffer',
  'nvim-autopairs',
]
on_event = 'VimEnter'
hook_post_source = '''
lua << EOF
local cmp = require('cmp')

cmp.setup({
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },
  window = {
    -- completion = cmp.config.window.bordered(),
    -- documentation = cmp.config.window.bordered(),
  },
  mapping = cmp.mapping.preset.insert({
    ['<C-e>'] = cmp.mapping.abort(),
    ['<C-n>'] = cmp.mapping.select_next_item(),
    ['<C-p>'] = cmp.mapping.select_prev_item(),
    ['<CR>'] = cmp.mapping.confirm({ select = true }),
  }),
  sources = cmp.config.sources({
    { name = 'nvim_lsp' },
    -- { name = 'nvim_lsp_signature_help' },
    { name = 'vsnip' },
  },
  {
    { name = 'fuzzy_buffer' },
  })
})

-- Set configuration for specific filetype.
cmp.setup.filetype('gitcommit', {
  sources = cmp.config.sources({
    { name = 'cmp_git' }, -- You can specify the `cmp_git` source if you were installed it.
  }, {
    { name = 'buffer' },
  })
})

-- Use buffer source for `/` and `?` (if you enabled `native_menu`, this won't work anymore).
cmp.setup.cmdline({ '/', '?' }, {
  mapping = cmp.mapping.preset.cmdline(),
  sources = {
    { name = 'buffer' },
    { name = 'fuzzy_buffer' },
  }
})

-- Use cmdline & path source for ':' (if you enabled `native_menu`, this won't work anymore).
cmp.setup.cmdline(':', {
  mapping = cmp.mapping.preset.cmdline(),
  sources = cmp.config.sources({
    { name = 'path' }
  }, {
    { name = 'cmdline' }
  })
})

local cmp_autopairs = require('nvim-autopairs.completion.cmp')
cmp.event:on(
  'confirm_done', cmp_autopairs.on_confirm_done()
)

EOF
'''

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
if = 'has("nvim")'

[[plugins]]
repo = 'hrsh7th/cmp-buffer'
if = 'has("nvim")'

[[plugins]]
repo = 'hrsh7th/cmp-path'
if = 'has("nvim")'

[[plugins]]
repo = 'hrsh7th/cmp-cmdline'
if = 'has("nvim")'

[[plugins]]
repo = 'hrsh7th/cmp-vsnip'
if = 'has("nvim")'
depends = ['vim-vsnip']

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
if = 'has("nvim")'

[[plugins]]
repo = 'tzachar/cmp-fuzzy-buffer'
if = 'has("nvim")'
depends = ['fuzzy.nvim']

[[plugins]]
repo = 'tzachar/fuzzy.nvim'
if = 'has("nvim")'
depends = ['telescope-fzf-native.nvim']

