[tools]
node = "20"
deno = "latest"
terraform = "1.5.2"
usage = "latest"
go = "latest"
ruby = "latest"
python = "latest"
tmux = "latest"
"go:github.com/aquaproj/aqua/v2/cmd/aqua" = "latest"

[settings]
experimental = true

